stages:
  - build

build-linux-job:
  stage: build
  tags: [linux]
  script:
    - cmake -B build --preset 'clang-debug-dev' -DCMAKE_PREFIX_PATH="${PATH_TO_OGRE3D}"
    - cmake --build build

build-windows-job:
  stage: build
  tags: [windows]
  script:
    - cmake -B build --preset 'msvc-debug-dev' -DCMAKE_PREFIX_PATH="${PATH_TO_OGRE3D}"
    - cmake --build build
